name = "MetaICVI"
uuid = "778c5047-3e82-4d04-81b5-6fafe2d2d704"
authors = ["Sasha Petrenko"]
version = "0.1.0"

[deps]
ClusterValidityIndices = "2fefd308-f647-4698-a2f0-e90cfcbca9ad"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyCallJLD = "de320387-30cd-5f83-91a8-a6e0ae8b8444"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ScikitLearn = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
MLJ = "0.16"
JLD = "0.12"
PyCall = "1"
PyCallJLD = "0.2"
julia = "1.6"

[extras]
AdaptiveResonance = "3d72adc0-63d3-4141-bf9b-84450dd0395b"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[targets]
test = ["AdaptiveResonance", "DelimitedFiles", "Plots", "SafeTestsets", "Statistics", "Test", "UnicodePlots"]
